# Generated by Django 4.0.3 on 2022-03-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_allergen_allergen_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergen_product',
            name='name',
        ),
    ]
