# Generated by Django 4.0.3 on 2022-03-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_allergen_product_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergen_Product',
            new_name='AllergenProduct',
        ),
        migrations.AlterModelTable(
            name='allergenproduct',
            table='allergensproducts',
        ),
    ]
